#!/bin/sh
# properties = {"type": "single", "rule": "merge_sites", "local": false, "input": ["tmp/POG1801/tmp_bigWig/POG1801.uncorrected.bw", "tmp/POG1801/tmp_bigWig/POG1801.GC_corrected.bw"], "output": ["/projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/results/POG1801/POG1801.uncorrected.coverage.tsv", "/projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/results/POG1801/POG1801.GC_corrected.coverage.tsv", "tmp/POG1801/tmp_pybedtools2"], "wildcards": {"samples": "POG1801"}, "params": {"sample_name": "POG1801", "tmp_dir": "tmp", "results_dir": "/projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/results", "mappability_correction": "False", "GC_map_corrected_bw": "none", "mappability_bw": "/projects/pangen/analysis/hmac/applications/Griffin/Ref/k100.Umap.MultiTrackMappability.bw", "chrom_sizes_path": "/projects/pangen/analysis/hmac/applications/Griffin/Ref/hg38.standard.chrom.sizes", "sites_yaml": "/projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/config/sites.yaml", "griffin_scripts_dir": "/projects/pangen/analysis/hmac/applications/Griffin/scripts", "griffin_merge_sites_script": "/projects/pangen/analysis/hmac/applications/Griffin/scripts/griffin_merge_sites.py", "chrom_column": "Chrom", "position_column": "position", "strand_column": "Strand", "chroms": "chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22", "norm_window": "-5000 5000", "save_window": "-1000 1000", "center_window": "-30 30", "fft_window": "-960 960", "fft_index": 10, "smoothing_length": 165, "encode_exclude": "/projects/pangen/analysis/hmac/applications/Griffin/Ref/encode_unified_GRCh38_exclusion_list.bed", "centromeres": "/projects/pangen/analysis/hmac/applications/Griffin/Ref/hg38_centromeres.bed", "gaps": "/projects/pangen/analysis/hmac/applications/Griffin/Ref/hg38_gaps.bed", "patches": "/projects/pangen/analysis/hmac/applications/Griffin/Ref/hg38_fix_patches.bed", "alternative_haplotypes": "/projects/pangen/analysis/hmac/applications/Griffin/Ref/hg38_alternative_haplotypes.bed", "step": 15, "CNA_normalization": false, "individual": false, "smoothing": true, "exclude_outliers": true, "exclude_zero_mappability": true, "number_of_sites": "none", "sort_by": "none", "ascending": "none", "CPU": 16}, "log": [], "threads": 1, "resources": {}, "jobid": 57, "cluster": {"mem": "32G", "ncpus": 16, "ntasks": 1, "output": "logs/cluster/merge_sites.POG1801.%A.out", "JobName": "merge_sites.POG1801"}}
 cd /projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling && \
/projects/steiflab/research/hmacdonald/applications/python/miniconda3/envs/griffin/bin/python3.7 \
-m snakemake /projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/results/POG1801/POG1801.GC_corrected.coverage.tsv --snakefile /projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/griffin_nucleosome_profiling.snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/.snakemake/tmp.p8j67kvy tmp/POG1801/tmp_bigWig/POG1801.uncorrected.bw tmp/POG1801/tmp_bigWig/POG1801.GC_corrected.bw --latency-wait 60 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
   --allowed-rules merge_sites --nocolor --notemp --no-hooks --nolock \
--mode 2  && touch /projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/.snakemake/tmp.p8j67kvy/57.jobfinished || (touch /projects/pangen/analysis/hmac/applications/Griffin/snakemakes/griffin_nucleosome_profiling/.snakemake/tmp.p8j67kvy/57.jobfailed; exit 1)

